#!/usr/bin/env python3
"""Source-integrity checks for memex-fwd.cpp.

Not a linter and not a substitute for the compiler. It looks for exactly the two classes of
damage that a SCRIPTED edit does and a compiler does not catch, both of which have already
happened to this file:

  1. A patch anchor that slipped, leaving a duplicated line - in our case a second
     `struct Graph {`. The compiler does catch that one, but only after a fifteen-minute
     build, and the error it gives points at the end of the file rather than at the
     duplication. A brace-balance check finds it in a second.

  2. A printf whose "\\n" is a literal backslash followed by n instead of a newline escape.
     This happens when a replacement string is generated by a tool with different escaping
     rules from C's - a Python raw string, or a shell heredoc that collapses doubled
     backslashes on the way through. THE COMPILER CANNOT SEE THIS. "...\\n" is a perfectly
     valid C string. The only symptom is output that runs together on one line, which reads
     as a formatting slip rather than as a corrupted patch, and it will be copied forward by
     the next person who edits nearby.

Run it after any scripted edit and before any build:

    python examples/memex-fwd/check_source.py

Exit status is non-zero if anything is wrong, so it can go in front of a build in a script.
"""

import os
import sys

BS = chr(92)   # a backslash, spelled this way so that no tool in the chain can mangle it
LF = chr(10)   # and a newline, and a double quote, for the same reason
QUOTE = chr(34)

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT = os.path.join(HERE, "memex-fwd.cpp")


def read(path):
    with open(path, encoding="utf-8") as f:
        return f.read()


def strip_literals(src):
    """Yield (index, char) for code outside comments, strings and char literals."""
    i, n = 0, len(src)
    line = 1
    while i < n:
        ch = src[i]
        if ch == "\n":
            line += 1
            i += 1
            continue
        if ch == "/" and i + 1 < n and src[i + 1] == "/":
            while i < n and src[i] != "\n":
                i += 1
            continue
        if ch == "/" and i + 1 < n and src[i + 1] == "*":
            i += 2
            while i + 1 < n and not (src[i] == "*" and src[i + 1] == "/"):
                if src[i] == "\n":
                    line += 1
                i += 1
            i += 2
            continue
        if ch == '"':
            i += 1
            while i < n and src[i] != '"':
                if src[i] == BS:
                    i += 1
                i += 1
            i += 1
            continue
        if ch == "'":
            # a char literal, if a closing quote turns up within a few characters;
            # otherwise it is something else entirely and we just move on
            j, closed = i + 1, False
            while j < n and j < i + 6:
                if src[j] == "'":
                    closed = True
                    break
                if src[j] == BS:
                    j += 1
                j += 1
            if closed:
                i = j + 1
                continue
            i += 1
            continue
        yield line, ch
        i += 1


def check_balance(src):
    """Braces, parens and brackets, ignoring comments and literals."""
    stack = []
    for line, ch in strip_literals(src):
        if ch in "{([":
            stack.append((ch, line))
        elif ch in ")]}":
            want = {")": "(", "]": "[", "}": "{"}[ch]
            if not stack or stack[-1][0] != want:
                top = stack[-1] if stack else None
                return ["line %d: '%s' closes %s" % (line, ch, top)]
            stack.pop()
    if stack:
        return ["unclosed '%s' opened at line %d (a patch anchor probably slipped and "
                "duplicated a line)" % (stack[-1][0], stack[-1][1])]
    return []


def check_escaped_newlines(src):
    """String literals holding a literal backslash-n. The compiler cannot see these.

    Only string literals in CODE are examined. Comments are skipped deliberately: the header
    of memex-fwd.cpp describes this very bug and has to be able to spell it out, and a check
    that fires on its own documentation is a check that gets switched off.
    """
    bad = []
    seq = BS + BS + "n"
    i, n = 0, len(src)
    line = 1
    while i < n:
        ch = src[i]
        if ch == "\n":
            line += 1
            i += 1
            continue
        if ch == "/" and i + 1 < n and src[i + 1] == "/":
            while i < n and src[i] != "\n":
                i += 1
            continue
        if ch == "/" and i + 1 < n and src[i + 1] == "*":
            i += 2
            while i + 1 < n and not (src[i] == "*" and src[i + 1] == "/"):
                if src[i] == "\n":
                    line += 1
                i += 1
            i += 2
            continue
        if ch == '"':
            start, startline = i, line
            i += 1
            while i < n and src[i] != '"':
                if src[i] == BS:
                    i += 1
                if i < n and src[i] == "\n":
                    line += 1
                i += 1
            i += 1
            lit = src[start:i]
            if seq in lit:
                bad.append("line %d: literal backslash-n in a string literal: %s"
                           % (startline, lit[:100]))
            continue
        i += 1
    return bad


def check_unterminated_strings(src):
    """A string literal broken across a real line break.

    The compiler does catch this one, so it is here for the fifteen minutes it saves rather
    than for the bug it finds. It is the third class of scripted-edit damage this file has
    seen, and it arrives the same way the doubled backslash does - through a generator that
    writes a real newline where C wanted the two characters backslash and n. That makes it
    the mirror image of check number 2, and a checker that finds one and not the other is
    half a checker. (Written after exactly this happened: a heredoc collapsed "\n\n" to a
    newline inside a printf, and the three checks above all reported ok.)

    C string literals may not contain a raw newline; only a backslash at the very end of the
    line continues one. No raw string literals in this file, so R"(...)" is not handled.
    """
    bad = []
    i, n = 0, len(src)
    line = 1
    while i < n:
        ch = src[i]
        if ch == LF:
            line += 1
            i += 1
            continue
        if ch == "/" and i + 1 < n and src[i + 1] == "/":
            while i < n and src[i] != LF:
                i += 1
            continue
        if ch == "/" and i + 1 < n and src[i + 1] == "*":
            i += 2
            while i + 1 < n and not (src[i] == "*" and src[i + 1] == "/"):
                if src[i] == LF:
                    line += 1
                i += 1
            i += 2
            continue
        if ch == QUOTE:
            startline = line
            i += 1
            while i < n and src[i] != QUOTE:
                if src[i] == BS:
                    # A backslash at the end of a line legally continues the literal;
                    # anything else it escapes cannot be the newline we are looking for.
                    i += 1
                    if i < n and src[i] == LF:
                        line += 1
                    i += 1
                    continue
                if src[i] == LF:
                    bad.append("line %d: string literal runs past the end of the line - a "
                               "real newline where C wanted backslash-n" % startline)
                    line += 1
                    break
                i += 1
            if i < n and src[i] == QUOTE:
                i += 1
            continue
        i += 1
    return bad


def check_adjacent_duplicates(src):
    """Two identical adjacent non-trivial lines - the other shape of a slipped anchor."""
    skip = {"", "}", "};", "//", "#endif", "#else", "break;", "return;"}
    bad = []
    lines = src.split("\n")
    for i in range(1, len(lines)):
        a, b = lines[i - 1].strip(), lines[i].strip()
        if a and a == b and a not in skip and not a.startswith("//") and len(a) > 6:
            bad.append("line %d: duplicated line: %s" % (i + 1, a[:100]))
    return bad


def main(argv):
    path = argv[1] if len(argv) > 1 else DEFAULT
    src = read(path)
    problems = []
    for name, fn in (("brace balance", check_balance),
                     ("escaped newlines", check_escaped_newlines),
                     ("unterminated strings", check_unterminated_strings),
                     ("adjacent duplicates", check_adjacent_duplicates)):
        found = fn(src)
        print("%-22s %s" % (name, "ok" if not found else "%d PROBLEM(S)" % len(found)))
        problems.extend(found)
    if problems:
        print()
        for p in problems:
            print("  " + p)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
